name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: notify
      uses: wei/curl@master
      with:
        args: https://sctapi.ftqq.com/${{SERVER_JIANG}}.send?title=blog