name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: tsq/tsq.github.io
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: dist
        CNAME: https://tsq.me